services:
  db:
    image: postgres:15-alpine
    container_name: postgres_db
    environment:
      POSTGRES_DB: meta_post_analyzer
      POSTGRES_USER: ${DB_USERNAME}
      POSTGRES_PASSWORD: ${DB_PASSWORD}
    ports:
      - "5432:5432"
    volumes:
      - postgres_data:/var/lib/postgresql/data
    networks:
      - app-network

  app:
    build: .
    container_name: spring_app
    ports:
      - "8080:8080"
    depends_on:
      - db
    environment:
      - PORT=8080
      - META_POST_LIMIT=${META_POST_LIMIT}
      - SCHEDULER_CRON=${SCHEDULER_CRON}
      - SPRING_DATASOURCE_URL=jdbc:postgresql://db:5432/meta_post_analyzer
      - SPRING_DATASOURCE_USERNAME=${DB_USERNAME}
      - SPRING_DATASOURCE_PASSWORD=${DB_PASSWORD}
    networks:
      - app-network

volumes:
  postgres_data:

networks:
  app-network:
    driver: bridge