spring:
  application:
    name: meta-post-analyzer

  datasource:
    url: ${DB_URL}
    username: ${DB_USERNAME}
    password: ${DB_PASSWORD}

  jpa:
    hibernate:
      ddl-auto: update
    show-sql: false
    properties:
      hibernate:
        format_sql: true

meta:
  graph:
    base-url: https://graph.facebook.com/v19.0
    access-token: ${META_ACCESS_TOKEN}
    page-id: ${META_PAGE_ID}
    post-limit: ${META_POST_LIMIT}

scheduler:
  cron: ${SCHEDULER_CRON}

server:
  port: ${PORT}

logging:
  level:
    az.edu.ingressacademy: DEBUG
    org.springframework.web: INFO

springdoc:
  swagger-ui:
    path: /swagger-ui.html
    operationsSorter: alpha
  api-docs:
    path: /v3/api-docs

  packages-to-scan: az.edu.ingressacademy.controller